"""``compose`` — (dataset, processing) -> ``Snakefile`` + ``config.yaml`` + ``units.tsv``.

**Emit data, never code (R1).** The composer selects a hand-written, versioned module and emits its
*configuration*; it never writes rule source. It is a pure function of **both** its inputs plus two
versioned ones recorded in provenance (the KB and the workflow modules) — it needs no FASTQ on disk,
local or remote. Two inputs, still no I/O: a processing manifest is data, not a side channel.

Purity across *both* is what makes "same dataset + different processing = different pipeline, same
dataset hash" a fact rather than a hope. Output is keyed by ``run_id = H(dataset ⊕ processing ⊕ kb ⊕
workflow)``, so composing one dataset two ways yields two directories instead of the second silently
overwriting the first — which is what a fixed ``.seqforge/pipeline/`` path used to do, in exactly the
case the split exists to enable.

The machine-independent/machine-specific boundary lives here: the **manifest** carries URIs and a
``liulab-genome`` assembly id (R9); the **config** it compiles to is the resolved, machine-specific
instantiation, so paths appear here and only here.

The gate has three parts (design §4.1) — this module always runs the deterministic **params** gate;
``wiring`` (``snakemake -n -p``) now really runs, because `snakemake-minimal` is a declared
dependency; ``e2e`` (the real count-matrix run) is reported as ``skip``, never silently as ``pass``.

**The Snakefile is the deliverable, and it is emitted here, unconditionally.** It used to be written
inside ``wiring_gate`` — so the product of the compiler was a side effect of a validation step, and
that step returned early whenever ``snakemake`` was absent from PATH, which it always was. `compose`
exited 0 and emitted nothing a user could run. A gate may read the deliverable; it may not be the
reason the deliverable exists.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from ..io import DEFAULT_REGISTRY, OnlistNotAvailable, OnlistRegistry
from ..kb import load_spec
from ..kb.schema import Spec
from ..manifest.hash import run_id
from ..models.dataset import DatasetManifest
from ..models.processing import (
    DatasetPin,
    ProcessingManifest,
    Quantification,
    RuntimeEnv,
    SoloQuant,
)
from ..models.resolve import ComposeResult, ModuleSelection
from ..workflows import WorkflowModule, container_uri, get_module
from ..workspace import readable, state_dir
from .params import (
    derived_params,
    find_read_with_role,
    param_block_key,
    params_gate,
    processing_params,
    render_param,
)


class ComposeError(RuntimeError):
    """The manifest cannot be compiled (unknown chemistry/module, or an unresolvable whitelist)."""


#: Names of the artifacts a run directory carries, beside the wrapper that reads them.
_CONFIG_NAME = "config.yaml"
_UNITS_TSV_NAME = "units.tsv"
_SNAKEFILE_NAME = "Snakefile"

#: The run wrapper: **the deliverable**. A user submits this file.
#:
#: It is data, not code (R1): it names a hand-written module and points it at a config. There is no
#: rule body, no shell block, and no logic here — `test_the_generated_wrapper_contains_no_rule_source`
#: holds the line.
#:
#: **It uses `module` / `use rule *`, not `include:`, and that is load-bearing rather than stylistic.**
#: Snakemake's default target is the first rule defined in the *main* Snakefile, and an `include:`d
#: rule is not one — so the old `configfile:` + `include:` wrapper parsed clean, listed all three
#: rules, and then did **nothing at all** when run: "Nothing to be done", exit 0. Measured 2026-07-15;
#: the same module content inlined builds 3 jobs, and via `include:` builds 0. `use rule * from m as *`
#: re-declares the rules in this workflow, which makes `all` a real default target and `snakemake` with
#: no arguments do the right thing. This is also what design.md §4.1 specified all along.
_WRAPPER = """# GENERATED by `seqforge compose` -- this file is DATA: it names a hand-written module
# and points it at a config. Rule source is never generated (R1); the rules live in the module below,
# under version control, at the exact version this run is pinned to.
#
# Run it:  snakemake --profile <your-cluster-profile> --software-deployment-method apptainer
#
# The default target is `all`, which produces one <sample>.h5ad per sample in units.tsv (plus a
# <sample>.velocyto.h5ad when Velocyto is counted).
#
# `--software-deployment-method apptainer` is what makes the aligner rule run inside the
# liulab-runtime image named in config.yaml. WITHOUT IT SNAKEMAKE IGNORES THE `container:` DIRECTIVE
# ENTIRELY and STAR comes from your PATH -- the run still works, and is no longer pinned. Never
# needed for the packaging step, which runs in whatever environment has seqforge.
configfile: "config.yaml"


module {alias}:
    snakefile:
        "{snakefile}"
    config:
        config


use rule * from {alias} as *
"""


def _module_alias(name: str) -> str:
    """`map/starsolo` -> `starsolo`: a Snakemake module needs a Python-identifier-shaped name."""
    return name.rsplit("/", 1)[-1].replace("-", "_")


def render_wrapper(module_name: str, snakefile: Path) -> str:
    """The run wrapper's text, for the module `module_name` living at `snakefile`."""
    return _WRAPPER.format(alias=_module_alias(module_name), snakefile=snakefile.resolve())


@dataclass(frozen=True)
class ComposePlan:
    """The composed artifacts, before they are written (compose is a pure function of the manifest)."""

    config: dict[str, object]
    units: list[dict[str, str]]
    module: ModuleSelection
    spec: Spec
    #: relative path -> the registry name `rule onlist` will build it from. NOT the barcodes:
    #: see `_resolve_token` and workflows/map/starsolo.smk for why compose does not write 111 MB.
    onlist_files: dict[str, list[str]]


def plan(
    manifest: DatasetManifest,
    processing: ProcessingManifest,
    *,
    registry: OnlistRegistry | None = None,
    outdir: str = "results",
    fastq_dir: str | Path | None = None,
    sif_dir: str | Path | None = None,
) -> ComposePlan:
    """Build the config + units + module selection for one (dataset, processing) pair.

    Both inputs are positional and required. Composing one dataset two ways is literally two calls
    with one argument changed, producing two ``run_id``s over one unchanged ``dataset_hash``.

    ``threads`` is deliberately NOT an argument: it lives in ``processing.resources.threads``. Having
    it in both places was the same two-sources-of-truth disease this whole change is curing.
    ``outdir`` and ``fastq_dir`` stay arguments, because they are paths — machine facts, which R9
    forbids a manifest from carrying. ``threads`` is intent; a path is an invocation.

    ``fastq_dir`` is where this machine keeps the bytes. A manifest URI is a *relative* name (R9), so
    without it ``units.tsv`` carries bare basenames and the pipeline resolves them against the run
    directory — where the FASTQs are not. That is not a stricter kind of purity, it is a pipeline that
    cannot find its input. Given a directory, ``units.tsv`` carries resolved absolute paths: the
    manifest stays machine-independent and the *config* becomes the machine-specific instantiation,
    which is the boundary this module's docstring has always drawn. Still no I/O — the path is joined,
    never read, so ``plan`` stays pure and needs no FASTQ on disk.
    """
    registry = registry if registry is not None else DEFAULT_REGISTRY
    _check_pin(manifest, processing)
    chemistry = manifest.library.chemistry.value
    if not chemistry:
        raise ComposeError("manifest.library.chemistry is empty; nothing to compile")
    # A processing-equivalent class emits identical params by construction (§12), so the first
    # member compiles for all of them — that is exactly what makes the ambiguity benign.
    spec = load_spec(chemistry[0])
    try:
        module = get_module(spec.backend.module)
    except KeyError as exc:
        raise ComposeError(str(exc)) from exc

    onlist_files: dict[str, list[str]] = {}
    intent = processing.processing
    _check_env(intent.environment.value, module)
    # Two owners, one block (R14). The KB says how to PARSE; the processing manifest says what to
    # COUNT. params_gate proves the key sets stay disjoint and that both halves arrive verbatim.
    params = _resolve_params(manifest, spec, registry, onlist_files)
    # Derived before processing, both after the KB: three owners, one key each, and `param_owners`
    # is the definition all three agree on. A complex chemistry locates its barcodes by quadruple,
    # computed from the element model rather than hand-entered (see `derived_params`).
    params.update(derived_params(spec))
    params.update(
        {k: render_param(v) for k, v in processing_params(intent.quantification.value).items()}
    )

    config: dict[str, object] = {
        "chemistry": list(chemistry),
        "genome": {
            "assembly": intent.genome.value.assembly,
            "annotation": intent.genome.value.annotation_name,
        },
        # The env name RESOLVED to an image this machine can run. `config["env"]` used to sit here:
        # emitted, and read by no rule — the env was recorded and then ignored, so a pipeline ran
        # against whatever STAR happened to be on PATH. One key, one owner, and now something reads
        # it. The manifest still carries the env *name* (R9); this is its machine-specific rendering,
        # exactly like a fastq path.
        "container": container_uri(intent.environment.value, sif_dir),
        "threads": intent.resources.threads,
        "outdir": outdir,
        "read_files_in": _read_files_in(manifest, module),
        "samples": [s.sample_id for s in manifest.experiment.samples],
        # Emitted by the composer like every other key. It used to be injected by the run wrapper at
        # parse time, and `required_config` documented that arrangement — but the wrapper was written
        # inside a gate that could not run, so the injector named by the contract did not exist and
        # every compiled pipeline was one `KeyError` from the start. One owner, no special case.
        "units_tsv": _UNITS_TSV_NAME,
    }
    config[param_block_key(spec)] = params
    primary = _primary_feature(intent.quantification.value)
    if primary is not None:
        # Top level, NOT inside config["solo"] — that block must stay "every key is a STAR CLI flag"
        # for the gate's coverage check, and STARsolo has no --primaryFeature. Order in the manifest
        # is a seqforge-side annotation with no aligner-side referent (STARsolo writes one
        # Solo.out/<Feature>/ per value and does not care about order), so it gets projected out to
        # an explicit value rather than leaving a positional convention load-bearing for every
        # downstream reader.
        config["primary_feature"] = primary

    return ComposePlan(
        config=config,
        units=_units(manifest, fastq_dir),
        module=ModuleSelection(name=module.name, version=module.version, env=module.env),
        spec=spec,
        onlist_files=onlist_files,
    )


def _primary_feature(quant: Quantification) -> str | None:
    """Which ``Solo.out/<Feature>/`` is THE matrix for this run. ``None`` for bulk (no such split)."""
    return quant.features[0] if isinstance(quant, SoloQuant) else None


def _check_env(env: RuntimeEnv, module: WorkflowModule) -> None:
    """The recipe's runtime env must be the one the module needs. Refuse; never quietly correct.

    The env is read off the processing manifest, not off the module, because that is the artifact
    that *records the decision* — and `ProcessingSection` forbids unknown keys precisely so that a
    user's stated intent is never silently dropped. But a module knows what software it needs, and
    ``map/starsolo`` in an env with no STAR is not a preference, it is a run that dies on a node.

    So both are read and they must agree. Until `container:` landed, `processing.environment` was
    emitted into the config and read by nothing, while policy hardcoded ``"align-rna"`` beside a
    module that also declared it — two owners who could not disagree only because nobody asked
    either. Policy now asks the module, which makes this check redundant *for the default path* and
    load-bearing for the one where a user hand-writes a processing.yaml.
    """
    if env != module.env:
        raise ComposeError(
            f"processing.environment is {env!r} but module {module.name!r} needs {module.env!r}. "
            f"The env is what supplies the aligner, so this run would start in a container without "
            f"one. Drop the field to take the module's own env, or pick a module that wants {env!r}."
        )


def _check_pin(manifest: DatasetManifest, processing: ProcessingManifest) -> None:
    """A BOUND processing manifest must name this dataset. Never auto-repin (R13)."""
    pin = processing.dataset
    if pin is None:
        return  # a template: portable by design — that is what drives a corpus
    if pin.dataset_hash != manifest.provenance.dataset_hash:
        raise ComposeError(
            f"processing manifest {processing.processing_id!r} is pinned to dataset "
            f"{pin.dataset_hash[:12]}… but this dataset is "
            f"{manifest.provenance.dataset_hash[:12]}…. Re-run `seqforge processing new` against "
            f"this dataset, or drop the pin to make it a template."
        )


def compose(
    manifest: DatasetManifest,
    processing: ProcessingManifest,
    *,
    registry: OnlistRegistry | None = None,
    workspace: str | Path = ".",
    outdir: str = "results",
    fastq_dir: str | Path | None = None,
    sif_dir: str | Path | None = None,
    run_wiring_gate: bool = True,
) -> ComposeResult:
    """Compile a (dataset, processing) pair into a runnable configuration + run the compose gates."""
    p = plan(
        manifest, processing, registry=registry, outdir=outdir, fastq_dir=fastq_dir, sif_dir=sif_dir
    )

    # Keyed by the RUN, not by the workspace. A fixed `.seqforge/pipeline/` path meant recipe B
    # silently overwrote recipe A's config, units, and materialized onlists — and "one dataset, many
    # recipes" is precisely the case this whole change exists to enable.
    rid = run_id(
        dataset_hash=manifest.provenance.dataset_hash,
        processing_hash=processing.provenance.processing_hash,
        kb_version=manifest.provenance.kb_version,
        workflow_version=processing.provenance.workflow_version,
    )
    # `pipeline/default-a3f8c19d2b04/`, not `pipeline/a3f8c19d…696/`. The run_id stays the identity
    # -- it is what keeps two recipes over one dataset apart -- but the recipe already has a name and
    # printing it costs nothing. The pilot's workspace was a directory of 64-hex names in which
    # nothing said which pipeline was which.
    pipeline_dir = state_dir(workspace, "pipeline", readable(processing.processing_id, rid))
    pipeline_dir.mkdir(parents=True, exist_ok=True)
    config_path = pipeline_dir / _CONFIG_NAME
    units_path = pipeline_dir / _UNITS_TSV_NAME

    # The whitelists are NOT written here. `rule onlist` builds each one when a job needs it and
    # `temp()` deletes it after — see workflows/map/starsolo.smk. Compose used to expand 6 794 880
    # packed barcodes into 111 MB of text per run directory, at compile time, for a file STAR opens
    # once; compiling one dataset three ways cost a third of a gigabyte of identical bytes that
    # nothing ever cleaned up. What compose owes the pipeline is the whitelist's NAME, which is a
    # decision, and `_resolve_token` still verifies the registry can produce it before emitting one.
    config_path.write_text(yaml.safe_dump(p.config, sort_keys=True))
    units_path.write_text(_units_tsv(p.units))
    # The Snakefile is THE DELIVERABLE, so the composer writes it — always, unconditionally, like the
    # config beside it. It used to be written inside `wiring_gate`, which returned early when
    # `snakemake` was absent from PATH, and `snakemake` was in no dependency table: the product was a
    # side effect of a validation step that could not fire, so `compose` emitted no Snakefile at all.
    # A gate may now read this file; it may not be the reason it exists.
    module = get_module(p.module.name)
    snakefile_path = pipeline_dir / _SNAKEFILE_NAME
    snakefile_path.write_text(render_wrapper(module.name, module.snakefile))
    # The resolved, dataset-BOUND processing manifest that produced this config, beside it. R7 says
    # disk is state, not that disk is input: the default path takes no --processing and must still
    # leave behind exactly what decided the run.
    bound = (
        processing
        if processing.dataset is not None
        else processing.model_copy(
            update={
                "dataset": DatasetPin(
                    dataset_hash=manifest.provenance.dataset_hash,
                    accessions=list(manifest.experiment.accessions.value),
                )
            }
        )
    )
    (pipeline_dir / "processing.lock.yaml").write_text(
        yaml.safe_dump(bound.model_dump(mode="json"), sort_keys=True)
    )

    from .gates import e2e_gate, wiring_gate

    status, problems = params_gate(manifest, processing, p.spec, p.config)
    gate: dict[str, str] = {
        "params": status,
        "wiring": wiring_gate(pipeline_dir, p) if run_wiring_gate else "skip",
        "e2e": e2e_gate(),
    }

    preview: dict[str, object] = dict(p.config)
    # a failing gate must say WHY; the verdict alone is not actionable (R4's spirit)
    preview["params_problems"] = problems

    return ComposeResult(
        modules=[p.module],
        snakefile_path=str(snakefile_path.relative_to(Path(workspace))),
        config_path=str(config_path.relative_to(Path(workspace))),
        units_path=str(units_path.relative_to(Path(workspace))),
        gate=gate,  # type: ignore[arg-type]
        params_preview=preview,
    )


def _resolve_params(
    manifest: DatasetManifest,
    spec: Spec,
    registry: OnlistRegistry,
    onlist_files: dict[str, list[str]],
) -> dict[str, object]:
    """Render the KB backend params for a CLI, resolving every ``{onlist:alias}`` to a real path."""
    out: dict[str, object] = {}
    for key, value in spec.backend.params.items():
        if isinstance(value, list):
            rendered = [_resolve_token(v, spec, registry, onlist_files) for v in value]
            out[key] = " ".join(str(r) for r in rendered)
        else:
            out[key] = render_param(_resolve_token(value, spec, registry, onlist_files))
    return out


def _resolve_token(
    value: object, spec: Spec, registry: OnlistRegistry, onlist_files: dict[str, list[str]]
) -> object:
    if not (isinstance(value, str) and value.startswith("{onlist:") and value.endswith("}")):
        return value
    alias = value[len("{onlist:") : -1]
    ref = spec.onlists.get(alias)
    if ref is None:
        raise ComposeError(f"backend references undeclared onlist alias {alias!r}")
    name = ref.registry
    rel = f"onlists/{name}.txt"
    try:
        registry.packed(name)
    except OnlistNotAvailable as exc:
        raise ComposeError(
            f"onlist {name!r} is not materialized, so --soloCBwhitelist cannot be emitted: {exc}. "
            "Register it (URL + sha256) or run with a registry that can fetch it."
        ) from exc
    # Verified, not materialized. `registry.packed(name)` above is what proves the whitelist EXISTS
    # and is the declared barcode set -- refusing here, at compile time, is the R11 rung-3 promise
    # `compose` makes. What it must not do is write the 111 MB: that is `rule onlist`'s job, and
    # `temp()`'s. The name is recorded so the gate and the tests can still see which list was chosen.
    onlist_files[rel] = [name]
    return rel


def _read_files_in(manifest: DatasetManifest, module: WorkflowModule) -> dict[str, str]:
    """Map the manifest's reads to the keys the module hands its aligner.

    Dispatch is on the module's declared ``read_layout_kind``, **not** on its name. This was
    `if spec.backend.module == "map/starsolo": ... else: <bulk>`, which is a bug rather than an
    abstraction gap: it makes "not starsolo" mean "bulk paired-end", so any third module would have
    silently emitted `mate1`/`mate2` for a chemistry that has neither and produced a wrong command
    line with no error anywhere.
    """
    if module.read_layout_kind == "barcoded":
        cdna = find_read_with_role(manifest, "cDNA") or find_read_with_role(manifest, "gDNA")
        barcode = find_read_with_role(manifest, "CB")
        if cdna is None or barcode is None:
            raise ComposeError("a barcoded chemistry needs both a cDNA read and a CB-bearing read")
        return {"cdna": cdna.read_id, "barcode": barcode.read_id}
    reads = manifest.library.read_layout.reads
    if len(reads) < 2:
        raise ComposeError(f"bulk paired-end needs 2 reads, found {len(reads)}")
    return {"mate1": reads[0].read_id, "mate2": reads[1].read_id}


def _resolve_uri(uri: str, fastq_dir: str | Path | None) -> str:
    """A manifest URI -> the path this machine will actually open.

    A non-file scheme (``s3://``, ``https://``, a bare accession) is passed through untouched: it is
    not ours to resolve, and Snakemake storage plugins or a future `fetch` module own that. Only a
    relative local name gets joined to ``fastq_dir``.
    """
    if "://" in uri or fastq_dir is None:
        return uri
    return str((Path(fastq_dir) / uri).resolve())


def _units(manifest: DatasetManifest, fastq_dir: str | Path | None = None) -> list[dict[str, str]]:
    """One row per (sample, read role, file). Falls back to a single implicit sample."""
    by_uri = {f.uri: f for f in manifest.library.files}
    rows: list[dict[str, str]] = []
    samples = manifest.experiment.samples
    if not samples:
        for f in manifest.library.files:
            if f.read_id is not None:
                rows.append(
                    {
                        "sample_id": "sample1",
                        "read_id": f.read_id,
                        "path": _resolve_uri(f.uri, fastq_dir),
                    }
                )
        return rows
    for sample in samples:
        for uri in sample.file_uris:
            item = by_uri.get(uri)
            if item is None or item.read_id is None:
                continue  # unassigned (index/ignored) files never become units
            rows.append(
                {
                    "sample_id": sample.sample_id,
                    "read_id": item.read_id,
                    "path": _resolve_uri(item.uri, fastq_dir),
                }
            )
    return rows


def _units_tsv(rows: list[dict[str, str]]) -> str:
    header = ["sample_id", "read_id", "path"]
    lines = ["\t".join(header)]
    lines += ["\t".join(r[h] for h in header) for r in rows]
    return "\n".join(lines) + "\n"
