"""``compose`` — (dataset, processing) -> ``Snakefile`` + ``config.yaml`` + ``units.tsv``.

**Emit data, never code.** The composer selects a hand-written, versioned module and emits its
*configuration*; it never writes rule source. It is a pure function of **both** its inputs plus two
versioned ones recorded in provenance (the KB and the workflow modules) — it needs no FASTQ on disk,
local or remote. Two inputs, still no I/O: a processing manifest is data, not a side channel.

Purity across *both* is what makes "same dataset + different processing = different pipeline, same
dataset hash" a fact rather than a hope. Output is keyed by ``run_id = H(dataset ⊕ processing ⊕ kb ⊕
workflow)``, so composing one dataset two ways yields two directories instead of the second silently
overwriting the first — which is what a fixed ``.seqforge/pipeline/`` path used to do, in exactly the
case the split exists to enable.

The machine-independent/machine-specific boundary lives here: the **manifest** carries URIs and a
``liulab-genome`` assembly id; the **config** it compiles to is the resolved, machine-specific
instantiation, so paths appear here and only here.

The gate has three parts — this module always runs the deterministic **params** gate;
``wiring`` (``snakemake -n -p``) now really runs, because `snakemake-minimal` is a declared
dependency; ``e2e`` (the real count-matrix run) is reported as ``skip``, never silently as ``pass``.

**The Snakefile is the deliverable, and it is emitted here, unconditionally.** It used to be written
inside ``wiring_gate`` — so the product of the compiler was a side effect of a validation step, and
that step returned early whenever ``snakemake`` was absent from PATH, which it always was. `compose`
exited 0 and emitted nothing a user could run. A gate may read the deliverable; it may not be the
reason the deliverable exists.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import assert_never

import yaml

from ..io import DEFAULT_REGISTRY, OnlistNotAvailable, OnlistRegistry
from ..kb import KB_VERSION, load_spec
from ..kb.schema import Spec
from ..manifest.hash import run_id, spec_content_hash
from ..models.dataset import INDEX_ROLE, DatasetManifest, ReadDef
from ..models.processing import (
    DatasetPin,
    ProcessingManifest,
    Quantification,
    RuntimeEnv,
    SoloQuant,
)
from ..models.resolve import ComposeResult, GateVerdict, ModuleSelection, SampleAdmission
from ..pipeline import CONFIG_NAME, DEFAULT_OUTDIR, UNITS_TSV_NAME, CompiledPipeline
from ..resolve.group import lane_of, run_key
from ..workflows import WorkflowModule, container_uri, get_module, resolve_pipeline
from ..workspace import pipeline_dir, readable
from .admission import Admission, admit, render_record
from .chimera import components
from .params import (
    derived_params,
    find_read_with_role,
    param_block_key,
    params_gate,
    processing_params,
    render_param,
)


class ComposeError(RuntimeError):
    """The manifest cannot be compiled (unknown chemistry/module, or an unresolvable whitelist)."""


#: The run wrapper: **the deliverable**. A user submits this file.
#:
#: It is data, not code: it names a hand-written module and points it at a config. There is no
#: rule body, no shell block, and no logic here — `test_the_generated_wrapper_contains_no_rule_source`
#: holds the line.
#:
#: **It uses `module` / `use rule *`, not `include:`, and that is load-bearing rather than stylistic.**
#: Snakemake's default target is the first rule defined in the *main* Snakefile, and an `include:`d
#: rule is not one — so the old `configfile:` + `include:` wrapper parsed clean, listed all three
#: rules, and then did **nothing at all** when run: "Nothing to be done", exit 0. Measured 2026-07-15;
#: the same module content inlined builds 3 jobs, and via `include:` builds 0. `use rule * from m as *`
#: re-declares the rules in this workflow, which makes `all` a real default target and `snakemake` with
#: no arguments do the right thing.
_WRAPPER = """# GENERATED by `seqforge compose` -- this file is DATA: it names a hand-written module
# and points it at a config. Rule source is never generated; the rules live in the module below,
# `{snakefile}`, COPIED into this directory beside this Snakefile at the exact version this run is
# pinned to. The copy is deliberate: a run directory carries its own recipe, so it stays readable and
# reproducible even after it is moved off the machine that composed it -- no path back into an
# installed package. (Running it still needs `seqforge` and `genome` importable; the copy makes the
# pipeline legible, not standalone.)
#
# The default target is `all`, which produces one <sample>.h5ad per sample in units.tsv (plus a
# <sample>.velocyto.h5ad when Velocyto is counted).
#
# Passing snakemake `--software-deployment-method apptainer` is what makes the aligner rule run
# inside the liulab-runtime image named in config.yaml. WITHOUT IT SNAKEMAKE IGNORES THE `container:`
# DIRECTIVE ENTIRELY and STAR comes from your PATH -- the run still works, and is no longer pinned.
# Never needed for the packaging step, which runs in whatever environment has seqforge.
configfile: "{config}"


module {alias}:
    snakefile:
        "{snakefile}"
    config:
        config


use rule * from {alias} as *
"""


def _module_alias(name: str) -> str:
    """`map/starsolo` -> `starsolo`: a Snakemake module needs a Python-identifier-shaped name."""
    return name.rsplit("/", 1)[-1].replace("-", "_")


def render_wrapper(module_name: str, snakefile: str) -> str:
    """The run wrapper's text, for the module `module_name` at the LOCAL name `snakefile`.

    ``snakefile`` is a bare filename (``starsolo.smk``), not a package path: the composer copies the
    module into the run directory and the wrapper imports its neighbour, so the `snakefile:` line
    resolves relative to this Snakefile. Snakemake resolves a module's snakefile against the including
    file's directory, which is exactly where the copy lands.

    The ``configfile:`` line names the config by the same constant the composer writes it under, so
    the wrapper cannot end up pointing at a filename nothing produces.
    """
    return _WRAPPER.format(
        alias=_module_alias(module_name), snakefile=snakefile, config=CONFIG_NAME
    )


@dataclass(frozen=True)
class ComposePlan:
    """The composed artifacts, before they are written (compose is a pure function of the manifest)."""

    config: dict[str, object]
    units: list[dict[str, str]]
    module: ModuleSelection
    spec: Spec
    #: relative path -> the registry name `rule onlist` will build it from. NOT the barcodes:
    #: see `_resolve_token` and workflows/map/starsolo.smk for why compose does not write 111 MB.
    onlist_files: dict[str, list[str]]
    #: What the loaded spec's read floor admitted, or `None` when it declares none. The verdict lives
    #: here and never in the manifest: it is recomputed under whatever KB is loaded at compile time,
    #: so moving the floor changes this pipeline and leaves the dataset's identity where it was.
    admission: Admission | None = None


def plan(
    manifest: DatasetManifest,
    processing: ProcessingManifest,
    *,
    registry: OnlistRegistry | None = None,
    outdir: str = DEFAULT_OUTDIR,
    fastq_dir: str | Path | None = None,
    sif_dir: str | Path | None = None,
) -> ComposePlan:
    """Build the config + units + module selection for one (dataset, processing) pair.

    Both inputs are positional and required. Composing one dataset two ways is literally two calls
    with one argument changed, producing two ``run_id``s over one unchanged ``dataset_hash``.

    ``threads`` is deliberately NOT an argument: it lives in ``processing.resources.threads``. Having
    it in both places was the same two-sources-of-truth disease this whole change is curing.
    ``outdir`` and ``fastq_dir`` stay arguments, because they are paths — machine facts, which a
    machine-independent manifest forbids carrying. ``threads`` is intent; a path is an invocation.

    ``fastq_dir`` is where this machine keeps the bytes. A manifest URI is a *relative* name, so
    without it ``units.tsv`` carries bare basenames and the pipeline resolves them against the run
    directory — where the FASTQs are not. That is not a stricter kind of purity, it is a pipeline that
    cannot find its input. Given a directory, ``units.tsv`` carries resolved absolute paths: the
    manifest stays machine-independent and the *config* becomes the machine-specific instantiation,
    which is the boundary this module's docstring has always drawn. Still no I/O — the path is joined,
    never read, so ``plan`` stays pure and needs no FASTQ on disk.
    """
    registry = registry if registry is not None else DEFAULT_REGISTRY
    _check_pin(manifest, processing)
    chemistry = manifest.library.chemistry.value
    if not chemistry:
        raise ComposeError("manifest.library.chemistry is empty; nothing to compile")
    # A processing-equivalent class emits identical params by construction, so the first
    # member compiles for all of them — that is exactly what makes the ambiguity benign.
    spec = load_spec(chemistry[0])
    try:
        module = resolve_pipeline(spec)
    except KeyError as exc:
        raise ComposeError(str(exc)) from exc

    # The live KB's admission floor, applied here and recorded nowhere in the manifest. `None` for
    # every chemistry that declares no floor, which is every shipped entry but the plate one.
    admission = _admit(manifest, spec)
    admitted = (
        [s.sample_id for s in admission.admitted]
        if admission is not None
        else [s.sample_id for s in manifest.experiment.samples]
    )

    onlist_files: dict[str, list[str]] = {}
    intent = processing.processing
    _check_env(intent.environment.value, module)
    # A chimera is STATED, never detected: naming `ce11_ecHT115` as the assembly IS the claim that
    # this reference carries several organisms, and reading it costs a plain compile one call that
    # returns `None`. It sits here, beside the other module-versus-recipe agreement check, because
    # both answer "can the pipeline this chemistry binds to actually run what this recipe asks for" —
    # and because policy never sees a genome, which is what keeps a processing default from acquiring
    # an opinion about the reference. A module that declares a twin turns this refusal into a swap.
    named = components(intent.genome.value.assembly)
    if named is not None and module.chimeric_variant is None:
        raise ComposeError(
            f"assembly {intent.genome.value.assembly!r} is spelled like a chimera — components "
            f"{', '.join(repr(c) for c in named)} — but pipeline {module.name!r} declares no "
            f"chimeric twin, so nothing downstream of the aligner would know the alignments cover "
            f"more than one organism: one count table, both organisms' genes as its columns, at exit "
            f"0, and no number anywhere saying how much of the library was which. Compose against a "
            f"single component assembly instead. If this reference is not a chimera it is named like "
            f"one — an '_' in an assembly name is how a chimera spells its components."
        )
    # Two owners, one block. The KB says how to PARSE; the processing manifest says what to
    # COUNT. params_gate proves the key sets stay disjoint and that both halves arrive verbatim.
    params = _resolve_params(manifest, spec, registry, onlist_files)
    # Derived before processing, both after the KB: three owners, one key each, and `param_owners`
    # is the definition all three agree on. A complex chemistry locates its barcodes by quadruple,
    # computed from the element model rather than hand-entered (see `derived_params`).
    params.update(derived_params(spec))
    params.update(
        {k: render_param(v) for k, v in processing_params(intent.quantification.value).items()}
    )

    config: dict[str, object] = {
        "chemistry": list(chemistry),
        "genome": {
            "assembly": intent.genome.value.assembly,
            "annotation": intent.genome.value.annotation_name,
        },
        # The env name RESOLVED to an image this machine can run. `config["env"]` used to sit here:
        # emitted, and read by no rule — the env was recorded and then ignored, so a pipeline ran
        # against whatever STAR happened to be on PATH. One key, one owner, and now something reads
        # it. The manifest still carries the env *name*; this is its machine-specific rendering,
        # exactly like a fastq path.
        "container": container_uri(intent.environment.value, sif_dir),
        "threads": intent.resources.threads,
        # The advisory memory hint, in MB, so the finalize CRAM sort can be given a real `-m` budget
        # rather than single-threading samtools' default. An intent knob (like threads), never a
        # machine fact — the scheduler honours it when the user submits.
        "mem_mb": intent.resources.mem_gb * 1024,
        "outdir": outdir,
        "read_files_in": _read_files_in(manifest, module),
        # The POST-DROP list: the sample ids this pipeline is CONTRACTED to produce. A sample the
        # admission floor excluded was never contracted — it was kept out before the contract was
        # written — so listing it here would report it, forever, as a result that failed to arrive.
        "samples": admitted,
        # Emitted by the composer like every other key. It used to be injected by the run wrapper at
        # parse time, and `required_config` documented that arrangement — but the wrapper was written
        # inside a gate that could not run, so the injector named by the contract did not exist and
        # every compiled pipeline was one `KeyError` from the start. One owner, no special case.
        "units_tsv": UNITS_TSV_NAME,
    }
    config[param_block_key(spec)] = params
    primary = _primary_feature(intent.quantification.value)
    if primary is not None:
        # Top level, NOT inside config["solo"] — that block must stay "every key is a STAR CLI flag"
        # for the gate's coverage check, and STARsolo has no --primaryFeature. Order in the manifest
        # is a seqforge-side annotation with no aligner-side referent (STARsolo writes one
        # Solo.out/<Feature>/ per value and does not care about order), so it gets projected out to
        # an explicit value rather than leaving a positional convention load-bearing for every
        # downstream reader.
        config["primary_feature"] = primary

    return ComposePlan(
        config=config,
        units=_units(manifest, fastq_dir, admitted=frozenset(admitted)),
        module=ModuleSelection(name=module.name, version=module.version, env=module.env),
        spec=spec,
        onlist_files=onlist_files,
        admission=admission,
    )


def _admit(manifest: DatasetManifest, spec: Spec) -> Admission | None:
    """The loaded spec's read floor, applied — and the two states in which it refuses instead.

    Both refusals exist because the alternative is a silent one. A compile with every sample below the
    floor would emit an empty ``rule all`` and exit 0, which is the silent-success failure class; and
    a manifest that measured no read counts is not the same claim as a dataset of empty samples, so
    reading one as the other would drop every sample at the moment the compiler looks most confident.
    There is deliberately **no drop-rate gate** between them: a plate with 60% dud wells is real, and
    a rate threshold needs a number nobody can defend. The count is reported, not gated.
    """
    admission = admit(manifest, spec)
    if admission is None:
        return None
    if admission.unmeasured:
        raise ComposeError(
            f"{spec.identity.id} declares an admission floor of {admission.threshold} reads, but this "
            f"manifest carries no read count for "
            f"{', '.join(repr(s) for s in admission.unmeasured[:5])}"
            f"{' and others' if len(admission.unmeasured) > 5 else ''}. It was written before "
            f"per-file counts existed, and an unmeasured sample is not an empty one — reading it as "
            f"zero reads would drop it silently. Re-run `seqforge manifest fill` over the same "
            f"files: the counts land in provenance and the dataset hash does not move."
        )
    if not admission.admitted:
        raise ComposeError(
            f"{admission.summary}: every one is below the {admission.threshold}-read admission floor "
            f"{spec.identity.id} declares (`min_input_reads`), so this pipeline would be contracted to produce "
            f"nothing and would finish, empty, at exit 0. Deepest of them: "
            f"{max(admission.excluded.values(), default=0)} reads. Either these files are not the "
            f"library they are named for, or the sequencing run they came from failed."
        )
    return admission


def _primary_feature(quant: Quantification) -> str | None:
    """Which ``Solo.out/<Feature>/`` is THE matrix for this run. ``None`` for bulk (no such split)."""
    return quant.features[0] if isinstance(quant, SoloQuant) else None


def _check_env(env: RuntimeEnv, module: WorkflowModule) -> None:
    """The recipe's runtime env must be the one the module needs. Refuse; never quietly correct.

    The env is read off the processing manifest, not off the module, because that is the artifact
    that *records the decision* — and `ProcessingSection` forbids unknown keys precisely so that a
    user's stated intent is never silently dropped. But a module knows what software it needs, and
    ``map/starsolo`` in an env with no STAR is not a preference, it is a run that dies on a node.

    So both are read and they must agree. Until `container:` landed, `processing.environment` was
    emitted into the config and read by nothing, while policy hardcoded ``"align-rna"`` beside a
    module that also declared it — two owners who could not disagree only because nobody asked
    either. Policy now asks the module, which makes this check redundant *for the default path* and
    load-bearing for the one where a user hand-writes a processing.yaml.
    """
    if env != module.env:
        raise ComposeError(
            f"processing.environment is {env!r} but module {module.name!r} needs {module.env!r}. "
            f"The env is what supplies the aligner, so this run would start in a container without "
            f"one. Drop the field to take the module's own env, or pick a module that wants {env!r}."
        )


def _check_pin(manifest: DatasetManifest, processing: ProcessingManifest) -> None:
    """A BOUND processing manifest must name this dataset. Never auto-repin."""
    pin = processing.dataset
    if pin is None:
        return  # a template: portable by design — that is what drives a corpus
    if pin.dataset_hash != manifest.provenance.dataset_hash:
        raise ComposeError(
            f"processing manifest {processing.processing_id!r} is pinned to dataset "
            f"{pin.dataset_hash[:12]}… but this dataset is "
            f"{manifest.provenance.dataset_hash[:12]}…. Re-run `seqforge processing new` against "
            f"this dataset, or drop the pin to make it a template."
        )


def compose(
    manifest: DatasetManifest,
    processing: ProcessingManifest,
    *,
    registry: OnlistRegistry | None = None,
    workspace: str | Path = ".",
    outdir: str = DEFAULT_OUTDIR,
    fastq_dir: str | Path | None = None,
    sif_dir: str | Path | None = None,
    run_wiring_gate: bool = True,
    subdir: str | None = None,
) -> ComposeResult:
    """Compile a (dataset, processing) pair into a runnable configuration + run the compose gates.

    ``subdir`` roots the output one level deeper — ``seqforge/<subdir>/pipeline/…`` instead of
    ``seqforge/pipeline/…`` — so a heterogeneous project can compile one assay per subdirectory. It
    defaults to ``None`` (the flat, single-assay layout), which is byte-identical to before.
    """
    p = plan(
        manifest, processing, registry=registry, outdir=outdir, fastq_dir=fastq_dir, sif_dir=sif_dir
    )

    # Keyed by the RUN, not by the workspace. A fixed `.seqforge/pipeline/` path meant recipe B
    # silently overwrote recipe A's config, units, and materialized onlists — and "one dataset, many
    # recipes" is precisely the case this whole change exists to enable.
    # The LIVE knowledge base, not the one the manifest recorded at fill time. ADR-0037. `plan` above
    # read this KB for the params, the derived keys and the admission floor, so the config is a
    # function of it; hashing the fill-time value instead meant an old manifest compiled under a new
    # KB produced a different config at the same `run_id`, into the same directory, silently.
    # What is folded is now the ONE spec's processing half rather than a repository-wide version
    # string — the same claim at the granularity it was always about, since `p.spec` is the very
    # object all three of those readings went through. A knowledge-base release that leaves this
    # chemistry's params alone therefore leaves this dataset's directory where it is, and its
    # alignments findable; only an edit that would change an emitted byte moves it. The manifest's own
    # `kb_version` stays exactly what it is — the KB that decided its chemistry.
    rid = run_id(
        dataset_hash=manifest.provenance.dataset_hash,
        processing_hash=processing.provenance.processing_hash,
        spec_hash=spec_content_hash(p.spec),
        workflow_version=processing.provenance.workflow_version,
    )
    # `pipeline/default-a3f8c19d2b04/`, not `pipeline/a3f8c19d…696/`. The run_id stays the identity
    # -- it is what keeps two recipes over one dataset apart -- but the recipe already has a name and
    # printing it costs nothing. The pilot's workspace was a directory of 64-hex names in which
    # nothing said which pipeline was which.
    #
    # Written THROUGH the compiled-pipeline owner rather than through three private constants of our
    # own: the composer is one of five modules that has to agree on this layout, and it is the only
    # one that writes it, which is exactly why the names may not be its.
    pipeline = CompiledPipeline(
        pipeline_dir(workspace, readable(processing.processing_id, rid), subdir=subdir)
    )
    pipeline.directory.mkdir(parents=True, exist_ok=True)

    # The whitelists are NOT written here. `rule onlist` builds each one when a job needs it and
    # `temp()` deletes it after — see workflows/map/starsolo.smk. Compose used to expand 6 794 880
    # packed barcodes into 111 MB of text per run directory, at compile time, for a file STAR opens
    # once; compiling one dataset three ways cost a third of a gigabyte of identical bytes that
    # nothing ever cleaned up. What compose owes the pipeline is the whitelist's NAME, which is a
    # decision, and `_resolve_token` still verifies the registry can produce it before emitting one.
    pipeline.config_path.write_text(yaml.safe_dump(p.config, sort_keys=True))
    pipeline.units_path.write_text(_units_tsv(p.units))
    # The Snakefile is THE DELIVERABLE, so the composer writes it — always, unconditionally, like the
    # config beside it. It used to be written inside `wiring_gate`, which returned early when
    # `snakemake` was absent from PATH, and `snakemake` was in no dependency table: the product was a
    # side effect of a validation step that could not fire, so `compose` emitted no Snakefile at all.
    # A gate may now read this file; it may not be the reason it exists.
    # Copy the hand-written module in beside the wrapper, and point the wrapper at the local copy.
    # This is still "emit data, never code": the module is checked-in source COPIED verbatim, not
    # generated -- `test_shipped_modules_are_hand_written_not_generated` guards the source, and the
    # wrapper itself still carries no rule body. What the copy buys is a run directory that reads and
    # reproduces on its own, instead of a `snakefile:` line pointing at an absolute path inside
    # whatever seqforge checkout happened to compose it.
    module = get_module(p.module.name)
    local_module_name = module.snakefile.name
    shutil.copy2(module.snakefile, pipeline.directory / local_module_name)
    pipeline.snakefile.write_text(render_wrapper(module.name, local_module_name))
    # The resolved, dataset-BOUND processing manifest that produced this config, beside it. Disk is
    # state, not input: the default path takes no --processing and must still
    # leave behind exactly what decided the run.
    bound = (
        processing
        if processing.dataset is not None
        else processing.model_copy(
            update={
                "dataset": DatasetPin(
                    dataset_hash=manifest.provenance.dataset_hash,
                    accessions=list(manifest.experiment.accessions.value),
                )
            }
        )
    )
    (pipeline.directory / "processing.lock.yaml").write_text(
        yaml.safe_dump(bound.model_dump(mode="json"), sort_keys=True)
    )
    admission = _write_exclusions(pipeline, p.admission, manifest, Path(workspace))

    from .gates import e2e_gate, wiring_gate

    status, problems = params_gate(manifest, processing, p.spec, p.config)
    # A failing gate must say WHY; the verdict alone is not actionable. That principle lived here and
    # applied to `params` alone, because `params_problems` had nowhere to go but `params_preview` —
    # whose name would have lied the moment a second gate used it. It now rides on each verdict.
    gate = {
        "params": GateVerdict(status=status, reason=problems),
        "wiring": wiring_gate(pipeline.directory, p)
        if run_wiring_gate
        else GateVerdict(status="skip", reason=["the caller did not ask for the wiring gate"]),
        "e2e": e2e_gate(),
    }

    return ComposeResult(
        modules=[p.module],
        snakefile_path=str(pipeline.snakefile.relative_to(Path(workspace))),
        config_path=str(pipeline.config_path.relative_to(Path(workspace))),
        units_path=str(pipeline.units_path.relative_to(Path(workspace))),
        gate=gate,
        params_preview=dict(p.config),
        admission=admission,
        # Both, from the one place that already holds both. `rid` above folded the live value and
        # `plan` read that same knowledge base for the params; recording them here is what lets every
        # caller disclose the divergence without re-deriving which name to compare.
        kb_version=KB_VERSION,
        manifest_kb_version=manifest.provenance.kb_version,
    )


def _write_exclusions(
    pipeline: CompiledPipeline,
    admission: Admission | None,
    manifest: DatasetManifest,
    workspace: Path,
) -> SampleAdmission | None:
    """Write the exclusion record, and report what the floor did. ``None`` when no floor was applied.

    The record is written only when something was actually excluded: a compile that lost nothing has
    nothing to explain, and a file saying so in every run directory is noise on the datasets that are
    fine. The machine-readable half is returned either way, so a caller can still tell a floor that
    ran and admitted everything from one that was never declared.

    **The record-less caveat is decided here**, because this is where both of its conditions are in
    hand: at least one sample lost, and no sample anywhere in the deposit carrying an archive
    accession. With no accession the sample axis came from filenames, so a cell sequenced across two
    runs was gated as two half-cells — unfixable by construction, and therefore disclosed at the point
    of loss rather than raised as a Blocker that would refuse every record-less plate with an empty
    well, or as a fill-time warning that would fire on every record-less dataset before any drop
    exists.
    """
    if admission is None:
        return None
    record_path: str | None = None
    if admission.excluded:
        pipeline.exclusions_path.write_text(
            render_record(
                admission,
                chemistry=manifest.library.chemistry.value[0],
                filename_derived=all(s.accession is None for s in manifest.experiment.samples),
            )
        )
        record_path = str(pipeline.exclusions_path.relative_to(workspace))
    return SampleAdmission(
        threshold=admission.threshold,
        declared=admission.declared,
        excluded=admission.excluded,
        record_path=record_path,
        summary=admission.summary,
    )


def _resolve_params(
    manifest: DatasetManifest,
    spec: Spec,
    registry: OnlistRegistry,
    onlist_files: dict[str, list[str]],
) -> dict[str, object]:
    """Render the KB backend params for a CLI, resolving every ``{onlist:alias}`` to a real path."""
    out: dict[str, object] = {}
    for key, value in spec.require_backend().params.items():
        if isinstance(value, list):
            rendered = [_resolve_token(v, spec, registry, onlist_files) for v in value]
            out[key] = " ".join(str(r) for r in rendered)
        else:
            out[key] = render_param(_resolve_token(value, spec, registry, onlist_files))
    return out


def _resolve_token(
    value: object, spec: Spec, registry: OnlistRegistry, onlist_files: dict[str, list[str]]
) -> object:
    if not (isinstance(value, str) and value.startswith("{onlist:") and value.endswith("}")):
        return value
    alias = value[len("{onlist:") : -1]
    ref = spec.onlists.get(alias)
    if ref is None:
        raise ComposeError(f"backend references undeclared onlist alias {alias!r}")
    name = ref.registry
    rel = f"onlists/{name}.txt"
    try:
        registry.packed(name)
    except OnlistNotAvailable as exc:
        raise ComposeError(
            f"onlist {name!r} is not materialized, so --soloCBwhitelist cannot be emitted: {exc}. "
            "Register it (URL + sha256) or run with a registry that can fetch it."
        ) from exc
    # Verified, not materialized. `registry.packed(name)` above is what proves the whitelist EXISTS
    # and is the declared barcode set -- refusing here, at compile time, is the rung-3 promise
    # `compose` makes. What it must not do is write the 111 MB: that is `rule onlist`'s job, and
    # `temp()`'s. The name is recorded so the gate and the tests can still see which list was chosen.
    onlist_files[rel] = [name]
    return rel


def _read_files_in(manifest: DatasetManifest, module: WorkflowModule) -> dict[str, str]:
    """Map the manifest's reads to the keys the module hands its aligner.

    Dispatch is on the module's declared ``read_layout_kind``, **not** on its name. This was
    `if spec.backend.module == "map/starsolo": ... else: <bulk>`, which is a bug rather than an
    abstraction gap: it makes "not starsolo" mean "bulk paired-end", so any third module would have
    silently emitted `mate1`/`mate2` for a chemistry that has neither and produced a wrong command
    line with no error anywhere. Each kind is therefore named here and none is the fall-through —
    `assert_never` is what makes a fourth kind a type error at the dispatch it forgot, rather than a
    wrong command line the barcode-free branch happily emits.
    """
    kind = module.read_layout_kind
    if kind == "barcoded":
        cdna = find_read_with_role(manifest, "cDNA") or find_read_with_role(manifest, "gDNA")
        barcode = find_read_with_role(manifest, "CB")
        if cdna is None or barcode is None:
            raise ComposeError("a barcoded chemistry needs both a cDNA read and a CB-bearing read")
        return {"cdna": cdna.read_id, "barcode": barcode.read_id}
    if kind == "atac_barcoded":
        # scATAC: two GENOMIC mates + a separate barcode read (chromap's -1/-2/-b). The two gDNA reads
        # keep layout order (R1 before R3), which is arbitrary between symmetric mates but stable — the
        # units.tsv `run` column, not this order, is what pairs a pooled sample's files.
        gdna = _reads_with_role(manifest, "gDNA")
        barcode = find_read_with_role(manifest, "CB")
        if len(gdna) < 2 or barcode is None:
            raise ComposeError("scATAC needs two genomic (gDNA) reads and a barcode read")
        return {"gdna1": gdna[0].read_id, "gdna2": gdna[1].read_id, "barcode": barcode.read_id}
    if kind == "mates":
        # 1..2 biological mates chosen by ORDER, never by role: a bulk library has no barcode read to
        # name one by. Only the mates the layout HAS are emitted, so a single-end library composes to
        # `{mate1}` and `star.smk` renders STAR's own single-end `--readFilesIn` (ADR-0029). Emitting
        # a `mate2` key pointing at nothing would be the same lie in the other direction: the module
        # would declare an input the sample cannot supply.
        reads = manifest.library.read_layout.reads
        if not reads:
            raise ComposeError("a mates layout needs at least one read, found none")
        return {f"mate{n}": read.read_id for n, read in enumerate(reads[:2], start=1)}
    if kind == "umi_tagged":
        # A plate assay: one mate opens with tag + UMI + motif, the other is plain cDNA, and there is
        # no barcode read anywhere to name either by. Chosen by ROLE, and that is the whole reason
        # this kind exists: `mates` would take these two in ORDER, and they are NOT symmetric — a
        # layout listing the plain mate first would hand the untagged read to the extractor, tag
        # nothing, and finish with an empty matrix at exit 0.
        tagged = find_read_with_role(manifest, "UMI")
        if tagged is None:
            raise ComposeError(
                "a umi_tagged layout needs a read carrying a UMI element; this one carries none, so "
                "there is nothing for the extractor to lift out"
            )
        # The mate is optional, because the kind tolerates ONE read structurally — a single-end plate
        # is a real published configuration and must not need a fifth layout kind to express. The
        # extractor now takes it as an ADDITION rather than as half of the operation (ADR-0035), so a
        # placement carrying `umi_cdna` alone is one the module runs, not a promise it breaks at DAG
        # time — and this dispatch still never invents a mate that is not there.
        mate = next(
            (
                read
                for read in manifest.library.read_layout.reads
                if read.read_id != tagged.read_id
                and any(el.role in ("cDNA", "gDNA") for el in read.elements)
            ),
            None,
        )
        placement = {"umi_cdna": tagged.read_id}
        if mate is not None:
            placement["cdna"] = mate.read_id
        return placement
    assert_never(kind)


def _reads_with_role(manifest: DatasetManifest, role: str) -> list[ReadDef]:
    """Every layout read carrying an element of ``role``, in layout order (scATAC has two gDNA reads)."""
    return [
        read
        for read in manifest.library.read_layout.reads
        if any(el.role == role for el in read.elements)
    ]


def _resolve_uri(uri: str, fastq_dir: str | Path | None) -> str:
    """A manifest URI -> the path this machine will actually open.

    A non-file scheme (``s3://``, ``https://``, a bare accession) is passed through untouched: it is
    not ours to resolve, and Snakemake storage plugins or a future `fetch` module own that. Only a
    relative local name gets joined to ``fastq_dir``.
    """
    if "://" in uri or fastq_dir is None:
        return uri
    return str((Path(fastq_dir) / uri).resolve())


def _units(
    manifest: DatasetManifest,
    fastq_dir: str | Path | None = None,
    *,
    admitted: frozenset[str] | None = None,
) -> list[dict[str, str]]:
    """One row per (sample, run, lane, read role, file). Falls back to a single implicit sample.

    ``admitted`` is the post-drop sample list — a sample the loaded spec's read floor excluded gets no
    row, so the units table and ``config["samples"]`` say the same thing about what this pipeline
    produces. ``None`` means no floor was applied and every sample stands, which is the shipped state.

    ``run`` is which sequencing run a file came from, from the SAME `resolve.group.run_key` that
    grouped the dataset into runs during resolution. Recording it here is what lets the mapping module
    pair a pooled sample's mates by run: STAR reads `--readFilesIn` mate-by-mate and desyncs if cDNA of
    run K is joined with barcodes of run J, and `sample.file_uris` gives no order guarantee. Deriving
    the run once, in the one function that owns the notion, keeps the workflow from re-parsing names.

    ``lane`` is the rest of that guarantee, and it exists because the run key stopped carrying it. A
    run spans its lanes (ADR-0027), so a four-lane library is ONE run and ``run`` no longer separates
    its eight files — leaving the mates' order to the lexical path sort, which holds for bcl2fastq
    names by the coincidence of where the read token sits and fails SILENTLY when it does not: the two
    comma-lists still hold equal read counts, so STAR completes and writes a matrix pairing one lane's
    barcodes with another lane's cDNA. `resolve.group.lane_of` reads the same token `run_key` removed,
    so the column and the grouping cannot disagree; an unlaned name yields ``""``, which sorts before
    every lane and orders identically for every mate.
    """
    by_uri = {f.uri: f for f in manifest.library.files}
    rows: list[dict[str, str]] = []
    samples = manifest.experiment.samples
    if not samples:
        for f in manifest.library.files:
            if f.read_id is not None and f.read_id != INDEX_ROLE:
                rows.append(
                    {
                        "sample_id": "sample1",
                        "run": run_key(f.uri),
                        "lane": lane_of(f.uri),
                        "read_id": f.read_id,
                        "path": _resolve_uri(f.uri, fastq_dir),
                    }
                )
        return rows
    for sample in samples:
        if admitted is not None and sample.sample_id not in admitted:
            continue
        for uri in sample.file_uris:
            item = by_uri.get(uri)
            if item is None or item.read_id is None or item.read_id == INDEX_ROLE:
                continue  # unassigned files, and set-aside technical index reads, never become units
            rows.append(
                {
                    "sample_id": sample.sample_id,
                    "run": run_key(item.uri),
                    "lane": lane_of(item.uri),
                    "read_id": item.read_id,
                    "path": _resolve_uri(item.uri, fastq_dir),
                }
            )
    return rows


def _units_tsv(rows: list[dict[str, str]]) -> str:
    header = ["sample_id", "run", "lane", "read_id", "path"]
    lines = ["\t".join(header)]
    lines += ["\t".join(r[h] for h in header) for r in rows]
    return "\n".join(lines) + "\n"
